model: small
compute_type: int8

paths:
  input_dir: input
  audio_dir: audio
  output_dir: output
  log_dir: logs

youtube:
  urls:
    - https://www.youtube.com/watch?v=HDHQ8lAWakY
    # - "https://www.youtube.com/watch?v=ruxb9RjAv4E&list=PLW4OpyGE0RdY"
    # - https://www.youtube.com/watch?v=ahaLgJr3HcU&list=PLW4OpyGE0RdY
    # - "https://www.youtube.com/watch?v=Vl2WcqdizZ0&list=PLW4OpyGE0RdY"
    # - "https://www.youtube.com/watch?v=aF0IK2sIQyY&list=PLW4OpyGE0RdY"
    # - "https://www.youtube.com/watch?v=e7oU6ZCvRrw&list=PLW4OpyGE0RdY"
    # - "https://www.youtube.com/watch?v=j7Re_09T-co&list=PLW4OpyGE0RdY"